import { createSlice, createSelector } from '@reduxjs/toolkit';

const getId = () => (100000 * Math.random()).toFixed(0)

const anecdoteSlice = createSlice({
  name: 'anecdotes',
  initialState: [
    {
      content: 'If it hurts, do it more often',
      id: getId(),
      votes: 0
    },
    // Add your other initial anecdotes here
  ],
  reducers: {
    voteAnecdote(state, action) {
      const id = action.payload
      const anecdoteToVote = state.find(a => a.id === id)
      if (anecdoteToVote) {
        anecdoteToVote.votes += 1
      }
    },
    addAnecdote(state, action) {
      const content = action.payload
      state.push({
        content,
        id: getId(),
        votes: 0
      })
    }
  }
})

export const selectAnecdotes = (state) => state.anecdotes;

export const selectVisibleAnecdotes = createSelector(
  [selectAnecdotes, (state) => state.filter],
  (anecdotes, filter) => {
    return anecdotes
      .filter(anecdote => anecdote.content.toLowerCase().includes(filter.toLowerCase()))
      .sort((a, b) => b.votes - a.votes); // Sorting by votes
  }
);

// Export the action creators generated by createSlice
export const { voteAnecdote, addAnecdote } = anecdoteSlice.actions
export default anecdoteSlice.reducer
